### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by bhardwajhack** [masnun/phptube#5]
Notice: Undefined offset: 0 in D:\xampp\htdocs\phptube-master\PhpTube.php on line 27
array(0) { }

**Comment by tumanob** [comment]
Same for me.

**Comment by lun3xcoder** [comment]
same for me

**Comment by kamran-jabbar** [comment]
Same issue:
Notice: Undefined offset: 0  on line 25
array(0) { }

**Comment by HazNet** [comment]
Same for me.
